spring:
  datasource:
    username: admin
    password: Qwnmzxop10
    url: jdbc:postgresql://localhost:5433/usersDB
    driver-class-name: org.postgresql.Driver
  data:
    rest:
      enabled: false
      base-path: /api/data

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5433/usersDB
    user: admin
    password: Qwnmzxop10
    baseline-on-migrate: true

server:
  port: 8080
